global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert-rules.yml

scrape_configs:
  - job_name: nvr-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - nvr-service:8080

  - job_name: stream-gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - stream-gateway:8081
